=== nestorgarciacheste/Firulais/xml/ej2/2.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://ejemplo.com/alumnos"
           xmlns="http://ejemplo.com/alumnos"
           elementFormDefault="qualified">
  
  <xs:element name="alumnos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="alumno" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nia" type="xs:integer"/>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="nombre2" type="xs:string" minOccurs="0"/>
              <xs:element name="apellido1" type="xs:string"/>
              <xs:element name="apellido2" type="xs:string" minOccurs="0"/>
              <xs:element name="dni" type="xs:string"/>
              <xs:element name="nacimiento" type="xs:date"/>
              <xs:element name="nacionalidad" type="xs:string"/>
              <xs:element name="curso" type="xs:string"/>
              <xs:element name="modulo" type="xs:string" maxOccurs="unbounded"/>
              <xs:element name="notaMedia" type="xs:decimal"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== nestorgarciacheste/Firulais/xml/ej2/2.xml
<?xml version="1.0" encoding="UTF-8"?>
<alumnos xmlns="http://ejemplo.com/alumnos"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://ejemplo.com/alumnos file:/C:/Users/alumno/Documents/code/xml/ej2/2.xsd">
<alumno>
<nia>22234</nia>
<nombre>Elena</nombre>
<apellido1>Martos</apellido1>
<apellido2>Zamora</apellido2>
<dni>23486572D</dni>
<nacimiento>2002-10-07</nacimiento>
<nacionalidad>española</nacionalidad>
<curso>DAM1</curso>
<modulo>prog</modulo>
<modulo>si</modulo>
<modulo>bd</modulo>
<modulo>lmsgi</modulo>
<notaMedia>5.5</notaMedia>
</alumno>
<alumno>
<nia>29234</nia>
<nombre>Yuri</nombre>
<apellido1>Velosky</apellido1>
<dni>22983049D</dni>
<nacimiento>2003-05-05</nacimiento>
<nacionalidad>ucraniana</nacionalidad>
<curso>DAM1</curso>
<modulo>prog</modulo>
<modulo>bd</modulo>
<notaMedia>6.23</notaMedia>
</alumno>
<alumno>
<nia>27634</nia>
<nombre>Carlos</nombre>
<nombre2>Felipe</nombre2>
<apellido1>Sancho</apellido1>
<apellido2>Lita</apellido2>
<dni>23723472D</dni>
<nacimiento>1999-09-14</nacimiento>
<nacionalidad>española</nacionalidad>
<curso>DAM1</curso>
<modulo>prog</modulo>
<modulo>si</modulo>
<modulo>bd</modulo>
<modulo>lmsgi</modulo>
<notaMedia>7.15</notaMedia>
</alumno>
</alumnos>
