=== nestorgarciacheste/Firulais/xml/ej2/7.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="jugadores">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="jugador" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="edad" type="xs:positiveInteger"/>
              <xs:element name="nacionalidad" type="xs:string"/>
              <xs:element name="apodo" type="xs:string" minOccurs="0"/>
              <xs:element name="posicion">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="portero"/>
                    <xs:enumeration value="defensa"/>
                    <xs:enumeration value="medio campo"/>
                    <xs:enumeration value="delantero"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="email" minOccurs="0" maxOccurs="unbounded">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="equipo" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="lesionado" type="xs:boolean" default="false"/>
          </xs:complexType>
          <xs:key name="jugadorKey">
            <xs:selector xpath="jugador"/>
            <xs:field xpath="nombre"/>
          </xs:key>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== nestorgarciacheste/Firulais/xml/ej2/7.xml
<?xml version="1.0" encoding="UTF-8"?>
<jugadores xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/alumno/Documents/code/xml/ej2/7.xsd">
  <jugador lesionado="false">
    <nombre>Lionel Messi</nombre>
    <edad>34</edad>
    <nacionalidad>Argentina</nacionalidad>
    <posicion>delantero</posicion>
    <email>lionel.messi@gmail.com</email>
    <email>lionel.messi@fcbarcelona.es</email>
    <equipo>FC Barcelona</equipo>
  </jugador>
  <jugador lesionado="true">
    <nombre>Jan Oblak</nombre>
    <edad>29</edad>
    <nacionalidad>Eslovenia</nacionalidad>
    <apodo>The Wall</apodo>
    <posicion>portero</posicion>
    <email>jan.oblak@atleticodemadrid.com</email>
    <email>oblak@yahoo.com</email>
    <equipo>Atlético de Madrid</equipo>
  </jugador>
</jugadores>
